"""add payment management tables

Revision ID: 6a0f9777a5cb
Revises: aeecd8f99d6d
Create Date: 2026-07-29 19:27:24.256792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0f9777a5cb'
down_revision: Union[str, Sequence[str], None] = 'aeecd8f99d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('bill_period_start', sa.Date(), nullable=False),
    sa.Column('bill_period_end', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_bills_id'), 'customer_bills', ['id'], unique=False)
    op.create_table('customer_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('milk_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['customer_bills.id'], ),
    sa.ForeignKeyConstraint(['milk_type_id'], ['milk_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_bill_items_id'), 'customer_bill_items', ['id'], unique=False)
    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['customer_bills.id'], ),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_payments_id'), 'customer_payments', ['id'], unique=False)
    op.add_column('milk_types', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milk_types', 'unit_price')
    op.drop_index(op.f('ix_customer_payments_id'), table_name='customer_payments')
    op.drop_table('customer_payments')
    op.drop_index(op.f('ix_customer_bill_items_id'), table_name='customer_bill_items')
    op.drop_table('customer_bill_items')
    op.drop_index(op.f('ix_customer_bills_id'), table_name='customer_bills')
    op.drop_table('customer_bills')
    # ### end Alembic commands ###
